steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west4-docker.pkg.dev/helmet-420718/helmet-repo/helmet-image",
        ".",
      ]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west4-docker.pkg.dev/helmet-420718/helmet-repo/helmet-image",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "api",
        "--image",
        "europe-west4-docker.pkg.dev/helmet-420718/helmet-repo/helmet-image",
        "--region",
        "europe-west4",
      ]
