version: "3.8"

services:
  # api:
  #   build: ./api
  #   container_name: api
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - ./api:/app
  #   networks:
  #     - my-network
  # client:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SERVER_URL: "http://api:4000"
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://api:4000
    networks:
      - my-network

networks:
  my-network:
